// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: prayers.sql

package database

import (
	"context"
	"time"

	"github.com/google/uuid"
)

const createPrayer = `-- name: CreatePrayer :one
INSERT INTO prayers(id, created_at, updated_at, sender, receiver, prayer) 
VALUES (
    $1,
    $2,
    $3,
    $4,
    $5,
    $6
)
RETURNING id, created_at, updated_at, sender, receiver, prayer
`

type CreatePrayerParams struct {
	ID        uuid.UUID
	CreatedAt time.Time
	UpdatedAt time.Time
	Sender    uuid.UUID
	Receiver  uuid.UUID
	Prayer    string
}

func (q *Queries) CreatePrayer(ctx context.Context, arg CreatePrayerParams) (Prayer, error) {
	row := q.db.QueryRowContext(ctx, createPrayer,
		arg.ID,
		arg.CreatedAt,
		arg.UpdatedAt,
		arg.Sender,
		arg.Receiver,
		arg.Prayer,
	)
	var i Prayer
	err := row.Scan(
		&i.ID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Sender,
		&i.Receiver,
		&i.Prayer,
	)
	return i, err
}

const getReceivedPrayersForUser = `-- name: GetReceivedPrayersForUser :many
SELECT id, created_at, updated_at, sender, receiver, prayer FROM prayers
WHERE prayers.receiver = $1
ORDER BY prayers.created_at DESC
LIMIT $2
`

type GetReceivedPrayersForUserParams struct {
	Receiver uuid.UUID
	Limit    int32
}

func (q *Queries) GetReceivedPrayersForUser(ctx context.Context, arg GetReceivedPrayersForUserParams) ([]Prayer, error) {
	rows, err := q.db.QueryContext(ctx, getReceivedPrayersForUser, arg.Receiver, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Prayer
	for rows.Next() {
		var i Prayer
		if err := rows.Scan(
			&i.ID,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.Sender,
			&i.Receiver,
			&i.Prayer,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getSentPrayersFromUser = `-- name: GetSentPrayersFromUser :many
SELECT id, created_at, updated_at, sender, receiver, prayer FROM prayers
WHERE prayers.sender = $1
ORDER BY prayers.created_at DESC
LIMIT $2
`

type GetSentPrayersFromUserParams struct {
	Sender uuid.UUID
	Limit  int32
}

func (q *Queries) GetSentPrayersFromUser(ctx context.Context, arg GetSentPrayersFromUserParams) ([]Prayer, error) {
	rows, err := q.db.QueryContext(ctx, getSentPrayersFromUser, arg.Sender, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Prayer
	for rows.Next() {
		var i Prayer
		if err := rows.Scan(
			&i.ID,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.Sender,
			&i.Receiver,
			&i.Prayer,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
