// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: prayers.sql

package database

import (
	"context"
	"time"

	"github.com/google/uuid"
)

const createPrayer = `-- name: CreatePrayer :one
INSERT INTO prayers(id, created_at, updated_at, sender, receiver, prayer) 
VALUES (
    $1,
    $2,
    $3,
    $4,
    $5,
    $6
)
RETURNING id, created_at, updated_at, sender, receiver, prayer
`

type CreatePrayerParams struct {
	ID        uuid.UUID
	CreatedAt time.Time
	UpdatedAt time.Time
	Sender    uuid.UUID
	Receiver  uuid.UUID
	Prayer    string
}

func (q *Queries) CreatePrayer(ctx context.Context, arg CreatePrayerParams) (Prayer, error) {
	row := q.db.QueryRowContext(ctx, createPrayer,
		arg.ID,
		arg.CreatedAt,
		arg.UpdatedAt,
		arg.Sender,
		arg.Receiver,
		arg.Prayer,
	)
	var i Prayer
	err := row.Scan(
		&i.ID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Sender,
		&i.Receiver,
		&i.Prayer,
	)
	return i, err
}
