name: ci 
on:
  pull_request:
    branches: [main, development]

jobs:

  tests:
    name: Tests
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version: "1.23.x"
      
      - name: Run Tests
        run: go test -cover ./...

      - name: Install gosec
        run: go install github.com/securego/gosec/v2/cmd/gosec@latest

      - name: Run Security Checks
        run: gosec -exclude-generated ./...


  style:
    name: Styling and Formatting
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version: "1.23.x"

      # This is to check multiple files, as suggested by ChatGPT
      - name: Check style
        run: |
          output=$(go fmt ./...)
          if [ -n "$output" ]; then
            echo "The following files are not formatted:"
            echo "$output"
            exit 1
          fi

      - name: Install staticcheck
        run: go install honnef.co/go/tools/cmd/staticcheck@latest

      - name: Run linting
        run: staticcheck ./...