on:
  push:
    branches: ["development"]

jobs:

  deploy:
    name: Deployment development
    runs-on: ubuntu-latest
    env:
      DB_URL: ${{ secrets.DATABASE_URL_DEV }}
    steps:

      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version: "1.23.x"

      - name: Build applications
        run: ./scripts/builddev.sh

      - id: 'auth'
        uses: 'google-github-actions/auth@v2'
        with:
          credentials_json: '${{ secrets.GCP_CREDENTIALS }}'

      - name: 'Set up Cloud SDK'
        uses: 'google-github-actions/setup-gcloud@v2'

      - name: 'Submit Build to Google Cloud'
        run: gcloud builds submit --tag us-west1-docker.pkg.dev/prayer-buddies/prayer-buddies-server-dev/prayer-buddies:latest .

      # Updating migration prior deployment, this ensures that the database is served correctly
      - name: 'Install Goose'
        run: go install github.com/pressly/goose/v3/cmd/goose@latest

      - name: 'Migrate Database up'
        run: ./scripts/migrateup.sh

      - name: 'Run Cloud Deploy'
        run: gcloud run deploy prayer-buddies --image us-west1-docker.pkg.dev/prayer-buddies/prayer-buddies-server-dev/prayer-buddies:latest --region us-central1 --allow-unauthenticated --project prayer-buddies --max-instances=4

